CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(30) NOT NULL
);

CREATE TABLE "teacher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "lastname" varchar(30) NOT NULL
);

CREATE TABLE "course_level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(30) NOT NULL
);

CREATE TABLE "course_video" (
  "id" SERIAL PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "url" varchar(100) NOT NULL
);

CREATE TABLE "course_category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(30) NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" int NOT NULL,
  "description" varchar(150) NOT NULL,
  "url" int NOT NULL,
  "level" int NOT NULL,
  "category" int NOT NULL,
  "teacher" int NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "password" varchar(25) NOT NULL,
  "age" int NOT NULL,
  "rol" int NOT NULL
);

ALTER TABLE "courses" ADD FOREIGN KEY ("level") REFERENCES "course_level" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category") REFERENCES "course_category" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "teacher" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("rol") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("url") REFERENCES "course_video" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("id") REFERENCES "courses" ("title");
